[tool.poetry]
name = "ohra"
version = "0.1.0"
description = ""
authors = ["artur"]
license = "BSD-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pandas = "^2.2.3"
scikit-learn = "^1.6.1"
ipykernel = "^6.29.5"
openpyxl = "^3.1.5"
matplotlib = "^3.10.0"
nltk = "^3.9.1"
requests = "^2.32.3"
openai = "^1.65.3"
black = "^25.1.0"
pydantic = "^2.10.6"
flask = "^3.1.0"
langchain-core = "^0.3.51"
langgraph = "^0.3.25"
langchain = {extras = ["openai"], version = "^0.3.23"}
paramiko = "^3.5.1"
twisted = "^24.11.0"
scapy = "^2.6.1"
zope-interface = "^7.2"
sentence-transformers = "^4.1.0"
geoip2 = "^5.1.0"
pycountry = "^24.6.1"
nbformat = "^5.10.4"
geopandas = "^1.1.0"
tabulate = "^0.9.0"
telnetlib3 = "^2.0.4"


[tool.poetry.group.dev.dependencies]
bandit = "^1.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
